[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://* data:; style-src 'self' 'unsafe-inline'; connect-src 'self' https://nuxdebclrfaugeoaxqwa.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'none'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"